#!/usr/bin/env bash
#loops from 0-10.
#prints bad luck for 4th iteration, good luck on 8th iteration,
#else prints Holberton School
i=1
while ((i<11));
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	let i++
done
