#!/usr/bin/env bash
#loops from 0-20.
#prints bad luck from China for 4th iteration,
#bad luck from Japan on 9th iteration,
#bad luck from Italy on 17 iteration
#else prints number
i=1
while ((i<21));
do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
		esac
	let i++
done
